[package]
name = "sys_rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12.0", features = ["full"] }
async-trait = "0.1.51"
futures = "0.3.17"

[dev-dependencies]
rand = "0.8.4"
